use_frameworks!

target 'MyLib_Example' do
  pod 'MyLib', :path => '../'

  target 'MyLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
